### ISSUE TITLE
Dynamic size

### ISSUE THREAD

**Issue by ChunchuanLv** [cvxgrp/cvxpylayers#41]
I am wondering whether dynamical sized problem definition can be made possible? In natural language processing and other applications, many times we have input of the same structure, but different size. Right now, we need to create a problem on the fly. Maybe, it is possible to accelerate the computing in this regard. Do you think this can be a future feature, or this is infeasible?

Chunchuan

**Comment by sbarratt** [comment]
At this point, we're sticking with fixed problem sizes, because this allows us to cache the matrices for canonicalization and retrieval, and makes an evaluation of the layer much faster.
Some ways to get around this:
- Create a bunch of CvxpyLayer objects, all with different problem sizes, and at runtime select the correct layer for your problem size.
- Create a single, large CvxpyLayer object that can handle all possible problem sizes. For example if your parameters define linear constraints A x <= b, make A and b as big as they could possibly be, and then when calling the layer only fill some of the entries of A and b and make the rest zero. This might be wasteful though.
