### ISSUE TITLE
Solver scs returned status Unbounded/Inaccurate

### ISSUE THREAD

**Issue by deepgradient** [cvxgrp/cvxpylayers#51]
I occasionally face the following error when using the package for different matrices **A** and **b**.  It does not happen permanently, but I have no idea when it happens. It especially happens when I set sigma_value in the following code to less than `1e-4`

`

    def tf_solver(A: np.ndarray, b: np.ndarray, sigma_value: float):
   
        A = tf.constant(A)
        b = tf.constant(b)
        x_tf = cp.Variable((A.shape[1]))
        A_tf = cp.Parameter(A.shape)
        b_tf = cp.Parameter((b.shape[0]))

        constraints = [cp.norm(A_tf @ x_tf - b_tf, p=2) <= sigma_value]
        objective = cp.Minimize(cp.norm(x_tf, p=1))
        problem = cp.Problem(objective, constraints)

        assert problem.is_dpp()

        cvxpylayer = cvxlayer(problem, parameters=[A_tf, b_tf], variables=[x_tf])

        with tf.GradientTape() as tape:
            x, = cvxpylayer(A, b)
            summed_solution = tf.math.reduce_sum(x)

        gradA, gradb = tape.gradient(summed_solution, [A, b])
        grad = [gradA, gradb]

        residue = tf.tensordot(A, x, 1) - b

        return x.numpy(), grad, residue.numpy()

`

---------------------------------------------------------------------------------------------------------------------------------
<ipython-input-37-2022279bee48> 69 cs_procedure
x, grad, residue = tf_solver(A=precond_bi_orthonormal_matrix, b=precond_func_sampling_vector, sigma_value=sigma_value)
csUtils.py 30 tf_solver
x, = cvxpylayer(A, b)
cvxpylayer.py 109 __call__
return compute(*parameters)
custom_gradient.py 258 __call__
return self._d(self._f, a, k)
custom_gradient.py 212 decorated
return _eager_mode_decorator(wrapped, args, kwargs)
custom_gradient.py 409 _eager_mode_decorator
result, grad_fn = f(*args, **kwargs)
cvxpylayer.py 108 <lambda>
lambda *parameters: self._compute(parameters, solver_args))
cvxpylayer.py 160 _compute
A=A, b=b, c=c, cone_dict=self.cones, **solver_args)
cone_program.py 212 solve_and_derivative
A, b, c, cone_dict, warm_start=warm_start, mode=mode, **kwargs)
cone_program.py 262 solve_and_derivative_internal
raise SolverError("Solver scs returned status %s" % status)
diffcp.cone_program.SolverError:
Solver scs returned status Unbounded/Inaccurate

**Comment by akshayka** [comment]
SCS is the underlying solver that finds a solution to the problem. The error message

```
diffcp.cone_program.SolverError:
Solver scs returned status Unbounded/Inaccurate
```

suggests that SCS failed to make good progress on solving this problem. In particular, your problem is definitely not unbounded (unbounded means the objective can be made infinitely negative, whereas your objective is lower bounded by 1), so it's likely the case that SCS just failed, which is unfortunate.

What's likely happening is that for small values of `sigma_value`, the data matrix corresponding to your problem is very poorly conditioned, causing SCS to fail. (SCS implements a first-order method that can be very sensitive to conditioning). Generally, you should try to scale your problems so that the numerical data are not too small or too large, and so that the numbers are all roughly of the same scale.

In this example, if `sigma_value` is really supposed to be very small, it might be better to just replace it with `0.0`, if that would make sense for your program (numerically, even with this constraint, you might find Ax - b to have norm very slightly greater than 1). If that doesn't work for your purposes, you might instead remove the constraint and add it to the objective with a regularizer, eg,

```
lambd = cp.Parameter(nonneg=True)
objective = cp.Minimize(cp.norm(x_tf, p=1) + lambd * cp.norm(A_tf @ x_tf - b_tf))
```

This second formulation should be better conditioned than the first, as long as `lambd` is not too large or too small.

**Comment by sankethvedula** [comment]
Hi @akshayka, 
Thanks for the clarification!
I've been struggling with similar bugs lately, the solver would somewhat randomly return ``Unbounded/Inaccurate`` and sometimes even ``Infeasible``.

Is ``cvxpylayers`` compatible with other solvers like MOSEK? Do you think it would solve this issue of first-order solvers?

Thanks!

**Comment by akshayka** [comment]
Hey @sankethvedula. SCS is inaccurate more often than we'd like (though in my experience, if the status is `Infeasible`, the problem is probably actually infeasible).

We definitely want to add support for other solves in the future. CVXPY Layers uses the package `diffcp` to differentiate through cone programs. Right now, `diffcp` only supports SCS, but there's an [open issue](https://github.com/cvxgrp/diffcp/issues/31) for supporting other solvers like MOSEK and ECOS, which implement interior-point methods. Once `diffcp` supports (say) MOSEK, CVXPY Layers could support it as well.

**Comment by deepgradient** [comment]
> lambd = cp.Parameter(nonneg=True)
> objective = cp.Minimize(cp.norm(x_tf, p=1) + lambd * cp.norm(A_tf @ x_tf - b_tf))

Dear Akshay,

The problem was resolved by changing the value of sgima_value from `1e-5` to `1e-2 ` fr now.
It would be really great to add more solver to `diffcp` and `cvxpylayers` subsequently.

For now, I closed the issue.
