### ISSUE TITLE
cvxpylayers with gpu

### ISSUE THREAD

**Issue by NazgulZaki** [cvxgrp/cvxpylayers#52]
Hi,
I was wondering if we can use cvxpylayers with gpu to minimize convex loss function with high dimension (high number of parameters to estimate) but one layer (not deep learning problem)?
Thank you.

Best regards,
Naz

**Comment by sbarratt** [comment]
How big (and sparse) is your problem? A good CPU/memory setup will normally be faster at solving the problem than a GPU.

**Comment by NazgulZaki** [comment]
Thank you for reply! I need to estimate 1000x1000 matrix of parameters using cvxpy, however it's very slow (takes 2 days). Is it possible to fasten it using cxpylayer, or do you advise to use cvxpy?

**Comment by akshayka** [comment]
You won't be able to make it any faster using CVXPY Layers.

Out of curiosity, what does your CVXPY problem look like? CVXPY's compilation is usually quite fast as long [as the problem is described in a vectorized fashion](https://github.com/cvxgrp/cvxpy/blob/master/examples/notebooks/building_models_with_fast_compile_times.ipynb).
