### ISSUE TITLE
huge memory cost in initialization with high dimension input

### ISSUE THREAD

**Issue by zcyang** [cvxgrp/cvxpylayers#66]
This may be related to #33 

I am trying cvxpylayer on a problem with dimension 4k. It takes quite a while to initialize the layer. Moreover, the memory cost is also huge with 400G consumption. The memory is NOT released after the initialization.

**Comment by akshayka** [comment]
It is likely related. Can you share code to reproduce the issue?

**Comment by zcyang** [comment]
Below is a simple example:

```
import cvxpy as cp
from cvxpylayers.torch import Cvxpylayer

n = 4000
L = cp.Parameter((n, n))
p = cp.Parameter((n, 1))
x = cp.Variable((n, 1))
obj = cp.Minimize(cp.sum_squares(L.T@x) - p.T@x)
cons = [x <= 1]
prob = cp.Problem(obj, cons)
opt = CvxpyLayer(prob, [L, p], [x])
```

**Comment by akshayka** [comment]
I see, so you have over 16 million scalar parameters. 

The memory usage is not too surprising (though very unfortunate), since the affine map from parameters to problem will be a matrix with 16 million columns and over 4000 rows. If the constraint matrix ends up being dense, 400 GB memory usage is conceivable. I guess one thing for us to check would be whether the constraint matrix actually is dense.

@SteveDiamond, for visibility. This memory usage is unfortunate, because to the user this problem probably doesn’t feel large (even though it has many scalar parameters).

In the future, we could introduce a notion of sparse parameters (ie, parameters with a fixed sparsity pattern), which might help in cases like this one. I’m not sure how else to accommodate problems like this.

**Comment by SteveDiamond** [comment]
I guess we could print a warning if the parameter size is large (so it would be clear that it's n = 1.6e7 rather than n=4e3). Definitely people can construct parameters with sparsity, or from a basis, and that would be more compact. In theory people can do this themselves:
``
base_P = ... a (n*n, k) matrix where k is number of true parameters
base_param = cp.Parameter(k)
P = cp.reshape(base_P@base_param, (n, n))
``

**Comment by zcyang** [comment]
In case there is no need to get the gradient of the big matrix P, I can treat it as a constant:

```
import numpy as np
import cvxpy as cp
from cvxpylayers.torch import Cvxpylayer

n = 4000
L = np.random.randn(n, n)
p = cp.Parameter((n, 1))
x = cp.Variable((n, 1))
obj = cp.Minimize(cp.sum_squares(L.T@x) - p.T@x)
cons = [x <= 1]
prob = cp.Problem(obj, cons)
opt = CvxpyLayer(prob, [L, p], [x])
```
However, L is different for every iteration, I need to initialize/construct the cvxpy layer every time L changes.

Is there any way to specify L so that CvxLayer takes it as input but does not derive the gradient (not declaring as cp.Parameter)? 

Thanks!

**Comment by zcyang** [comment]
@akshayka @SteveDiamond 

When L is a constant, the memory issue is resolved if we don't need the gradient w.r.t `L`.
```python
import cvxpy as cp
from cvxpylayers.torch import Cvxpylayer

n = 4000
L = np.random.randn(n, n)
p = cp.Parameter((n, 1))
x = cp.Variable((n, 1))
obj = cp.Minimize(cp.sum_squares(L.T@x) - p.T@x)
cons = [x <= 1]
prob = cp.Problem(obj, cons)
opt = CvxpyLayer(prob, [p], [x])
```
However, `opt` cannot take L as input if L needs to be different in each iteration.
Is there a way to declare L as a constant matrix without treating it as `Parameter`?
```python
L = constant big matrix without gradient
opt = CvxpyLayer(prob, [p, L], [x])
```

Thanks!

**Comment by SteveDiamond** [comment]
There isn't a way to remove the memory requirement for ``L``. Not computing the gradient would save computation, but not memory.

**Comment by akshayka** [comment]
You could try recreating the CVXPY Layer each time you use it, making L a constant. This will be somewhat slow, since the layer will recompile each time. But it will be faster than making L a parameter.

**Comment by zcyang** [comment]
Thanks for the helpful comment!

@SteveDiamond 

```python
import cvxpy as cp
from cvxpylayers.torch import CvxpyLayer
import numpy as np

n = 4000
m = 100
# L = np.random.randn(n, m)
L = cp.Parameter((n, m))
p = cp.Parameter((n, 1))
x = cp.Variable((n, 1))
obj = cp.Minimize(cp.sum_squares(L.T@x) - p.T@x)
cons = [x <= 1]
prob = cp.Problem(obj, cons)
opt = CvxpyLayer(prob, [p, L], [x])
```
It takes more than 250G and a long time to initialize.

While treating it as a constant
```python
import cvxpy as cp
from cvxpylayers.torch import CvxpyLayer
import numpy as np

n = 4000
m = 100
L = np.random.randn(n, m)
# L = cp.Parameter((n, m))
p = cp.Parameter((n, 1))
x = cp.Variable((n, 1))
obj = cp.Minimize(cp.sum_squares(L.T@x) - p.T@x)
cons = [x <= 1]
prob = cp.Problem(obj, cons)
opt = CvxpyLayer(prob, [p, L], [x])
```
takes 1s and 200M to initialize the layer.

So there is a significant difference between treating L as a parameter and constant.

@akshayka Yes, I am using the trick. But it would be ideal for Cvxlayer to take L as input but L is treated as a constant without gradient?

**Comment by SteveDiamond** [comment]
@zcyang I know that if you treat L as a constant that will be much faster, and also that you can reinitialize the layers. What I'm saying is that the intermediate point that you're asking for, initialize once and have L treated as something less than a parameter, is not really possible. Certainly you could avoid computing the gradient, but that's not a huge gain.

**Comment by zcyang** [comment]
Got it, thanks!
