### ISSUE TITLE
Quadratic form

### ISSUE THREAD

**Issue by convQP** [cvxgrp/cvxpylayers#77]
Hi, 

in the examples provided in [the blog](https://locuslab.github.io/2019-10-28-cvxpylayers/),

the objective for a quadratic form is defined as 

`obj = cp.Minimize(0.5*cp.sum_squares(Q_sqrt*x) + q.T @ x)`

for example in the `The OptNet QP` section, and also the  `Ellipsoid Projections` section uses the `cp.sum_squares` function.

Can someone explain why not `quad_form` is used ? For example:

`obj = cp.Minimize(0.5*cp.quad_form(Q,x) + q.T @ x)`

?

To my understanding, using `sum_squares` would be correct if the `Q` matrix has all entries set to zero, except for the diagonal entries. Only in this case, I see that `cp.sum_squares(Q_sqrt*x)` = `cp.quad_form(Q,x)`

Is this implicitly assumed in the examples ? 
Otherwise, how do you get a value like `q_{1,2} x_{1}x_{2}`, where `x_{i}` denotes the i-th component of `x`, and `q_{1,2}` is the entry of Q at position (1,2).

**Comment by sbarratt** [comment]
We use this because cp.quad_form(Q, x) is not DPP in Q (see, eg,
https://www.cvxpy.org/tutorial/advanced/index.html#what-is-dpp), but
cp.sum_squares(Q_sqrt*x) is DPP in Q_sqrt.

Q_sqrt is the matrix such that Q = Q_sqrt.TQ_sqrt, so these will in fact be
equal. That is, cp.quad_form(Q, x) = x^TQx = x^TQ_sqrt^T Q_sqrt x =
\|Q_sqrt x\|_2^2 = cp.sum_squares(Q_sqrt @ x).
